# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_platform', '0003_goods_goodsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Text')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Your email')),
                ('from_name', models.CharField(max_length=100, verbose_name='Your name')),
            ],
        ),
    ]
